name: GitHub Profile Graphics

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      # 🐍 Generate Snake
      - name: Generate Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 📈 Generate Activity Graph
      - name: Generate Activity Graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: ${{ github.repository_owner }}
          options: theme=react-dark&hide_border=true&area=true
          output_path: activity-graph.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Move Activity Graph
        run: |
          mkdir -p dist
          cp activity-graph.svg dist/activity-graph.svg

      # 🚀 Publish everything
      - name: Deploy Profile Graphics
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update profile graphics [skip ci]"
